spring.datasource.url=jdbc:mysql://localhost:3306/db
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#com.mysql.jdbc.Driver
spring.datasource.username=ramesh
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true




for aws rds dababase
==============================================================
spring.datasource.url=jdbc:mysql://mydb.cq7tfb2ozv6u.ap-south-1.rds.amazonaws.com:3306/db1
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#com.mysql.jdbc.Driver
spring.datasource.username=admin
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


for postgres
==================================================================
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.hibernate.show-sql=true
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=admin


spring.datasource.initialization-mode=always
spring.datasource.initialize=true
spring.datasource.schema=classpath:/schema.sql
spring.datasource.continue-on-error=true
